In [1]:
class Matrix:
    def __init__(self, matrix):
        self.matrix = matrix

    def T(self):
        _len = len(self.matrix)
        t_matrix = [[0 for i in range(_len)] for i in range(_len)]
        for i in range(_len):
            for j in range(_len):
                t_matrix[j][i] = self.matrix[i][j]
        return Matrix(t_matrix)

    def __add__(self, other):
        if isinstance(other, (int | float)):
            result_matrix = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[0])):
                    row.append(self.matrix[i][j] + other)
                result_matrix.append(row)
            return (result_matrix)
        elif isinstance(other, Matrix):
            result_matrix = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[0])):
                    row.append(self.matrix[i][j] + other.matrix[i][j])
                result_matrix.append(row)
            return (result_matrix)
    
    def __sub__(self, other):
        if isinstance(other, (int | float)):
            result_matrix = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[0])):
                    row.append(self.matrix[i][j] - other)
                result_matrix.append(row)
            return (result_matrix)
        
        elif isinstance(other, Matrix):
            result_matrix = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[0])):
                    row.append(self.matrix[i][j] - other.matrix[i][j])
                result_matrix.append(row)
            return (result_matrix)

    def __matmul__(self, other):
        if len(self.matrix[0]) != len(other.matrix):
            raise ValueError("Количество столбцов первой матрицы должно быть равно количеству строк второй матрицы")
        result_matrix = []
        for i in range(len(self.matrix)):
            row = []
            for j in range(len(other.matrix[0])):
                val = 0
                for k in range(len(other.matrix)):
                    val += self.matrix[i][k] * other.matrix[k][j]
                row.append(val)
            result_matrix.append(row)
        return (result_matrix)
    
    def __truediv__(self, other):
        if isinstance(other, (int | float)):
            result_matrix = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[0])):
                    row.append(self.matrix[i][j] / other)
                result_matrix.append(row)
            return (result_matrix)
        elif isinstance(other, Matrix):
            result_matrix = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[0])):
                    row.append(self.matrix[i][j] / other.matrix[i][j])
                result_matrix.append(row)
            return (result_matrix)
    
    def __mul__(self, other):
        if isinstance(other, (int | float)):
            result_matrix = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[0])):
                    row.append(self.matrix[i][j] * other)
                result_matrix.append(row)
            return (result_matrix)
        elif isinstance(other, Matrix):
            result_matrix = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[0])):
                    row.append(self.matrix[i][j] * other.matrix[i][j])
                result_matrix.append(row)
            return (result_matrix)

    def __eq__(self, other):
        result_matrix = []
        
        for i in range(len(self.matrix)):
            row = []
            for j in range(len(self.matrix[0])):
                row.append((self.matrix[i][j]) == (other.matrix[i][j]))
            result_matrix.append(row)
        return (result_matrix)
        
        
    def __repr__(self):
        return str(self.matrix)

In [2]:
# class Matrix:
#     def __init__(self, matrix):
#         self.matrix = matrix
    
#     def __len__(self):
#         return len(self.matrix)

#     def __repr__(self):
#         return str(self.matrix)

#     def __add__(self, other):
#         result = []
#         for i in range(len(self.matrix)):
#             row = []
#             for j in range(len(self.matrix[0])):
#                 row.append(self.matrix[i][j] + other)
#             result.append(row)
#         return Matrix(result)
    
#     def T(self):
#         result = []
#         for j in range(len(self.matrix[0])):
#             row = []
#             for i in range(len(self.matrix)):
#                 row.append(self.matrix[i][j])
#             result.append(row)
#         return Matrix(result)

#     def __sub__(self, other):
#         result = []
#         for i in range(len(self.matrix)):
#             row = []
#             for j in range(len(self.matrix[0])):
#                 row.append(self.matrix[i][j] - other)
#             result.append(row)
#         return Matrix(result)


#     def __truediv__(self, other):
#         if isinstance(other, (int, float)):
#             result = []
#             for i in range(len(self.matrix)):
#                 row = []
#                 for j in range(len(self.matrix[0])):
#                     row.append(self.matrix[i][j] / other)
#                 result.append(row)
#             return Matrix(result)

#     def __mul__(self, other):
#         result = []
#         for i in range(len(self.matrix)):
#             row = []
#             for j in range(len(other)):
#                 sum = 0
#                 for k in range(len(other)):
#                     sum += self.matrix[i][k] * other
#                 row.append(sum)
#             result.append(row)
#         return Matrix(result)
    
#     def __matmul__(self, other):
#         result_matrix = []
#         for i in range(len(self.matrix)):
#             row = []
#             for j in range(len(other)):
#                 val = 0
#                 for k in range(len(other)):
#                     val += self.matrix[i][k] * other
#                 row.append(val)
#             result_matrix.append(row)
#         return (result_matrix)

In [3]:
class Test:
    array = [[1, 2, 3], [1, 2, 3]]
    
    def __repr__(self):
        return str(self.array)
    
t = Test()
t

[[1, 2, 3], [1, 2, 3]]

In [4]:
# matrix1 = [
#     [1, 2],
#     [4, 5]
#     ]
# matrix2 = [
#     [5, 6],
#     [7, 8]
#     ]

# my_matrix1 = Matrix(matrix1)
# my_matrix2 = Matrix(matrix2)

# print(my_matrix1 @ my_matrix2)

# print(my_matrix1 + my_matrix2)

# print(my_matrix1 * my_matrix2)

# print(my_matrix1 / 2)

# print(my_matrix1.T())

In [5]:
%pip install -Uq numpy

import numpy as np

%pip install -q ipytest pytest

import ipytest
import pytest
ipytest.autoconfig()

You should consider upgrading via the 'c:\Users\User\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\User\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


Note: you may need to restart the kernel to use updated packages.


In [6]:
array1 = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

array2 = [[3, 9, 2],
          [3, 3, 4],
          [8, 2, 2]]

ft_matrix1 = Matrix(array1)
sc_matrix2 = Matrix(array2)

ts_matrix1 = np.array(array1)
ts_matrix2 = np.array(array2)


print((ft_matrix1 @ sc_matrix2) == (ts_matrix1 @ ts_matrix2))

print(ft_matrix1 @ sc_matrix2)
print(ts_matrix1 @ ts_matrix2)



[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[33, 21, 16], [75, 63, 40], [117, 105, 64]]
[[ 33  21  16]
 [ 75  63  40]
 [117 105  64]]


In [7]:
%%ipytest

matrix1 = Matrix([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
matrix2 = Matrix([[8, 4, 2],
           [3, 3, 3],
           [7, 1, 2]])
# number = 5


@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_add_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 + matrix2 == (np.array(matrix1.matrix) + np.array(matrix2.matrix))).all()
    ), 'add section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13.2]])
def test_matrix_add_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 + number == np.array(matrix1.matrix) + number).all()
    ), 'add section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_sub_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 - matrix2 == np.array(matrix1.matrix) - np.array(matrix2.matrix)).all()
    ), 'sub section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 12.2]])    
def test_matrix_sub_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 - number == np.array(matrix1.matrix) - number).all()
    ), 'sub section with matrix and number is not working right'
    
@pytest.mark.parametrize("matrix1", [matrix1])    
def test_matrix_transpose(matrix1: Matrix):
    assert (
        (matrix1.T().matrix == np.array(matrix1.matrix).T).all()
    ), 'transpose section is not working right'
    
# -----------------------------------------

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_mul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 * matrix2 == np.array(matrix1.matrix) * np.array(matrix2.matrix)).all()
    ), 'mul section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13]])
def test_matrix_mul_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 * number == np.array(matrix1.matrix) * number).all()
    ), 'mul section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])    
def test_matrix_div_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 / matrix2 == np.array(matrix1.matrix) / np.array(matrix2.matrix)).all()
    ), 'div section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 2]])    
def test_matrix_div_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 / number == np.array(matrix1.matrix) / number).all()
    ), 'div section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2.T()]])    
def test_matrix_matmul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert(
        (matrix1 @ matrix2 == np.array(matrix1.matrix) @ np.array(matrix2.matrix)).all()
    ), 'matmul section is not working right, and don\'t forget about T() if needed'

..........                                                                                   [100%]
10 passed in 0.09s
